Simple Implement Models
apmath-web/loans pull request #18
Opened 2019-03-23 05:36 UTC by Meleorina

- [x]  Implement Loan
- [x]  Implement Payment
- [x]  Implement LoanList
- [x]  Implement PaymentList
- [x]  Implement Message
close: #6

2019-03-29 20:02 UTC, BarracudaPff commented
@Meleorina 
Merge with [dev](https://github.com/apmath-web/loans/tree/dev)

2019-04-02 16:52 UTC, Meleorina commented
@malinink 
Где должны лежать функции? Только в `LoanEmployeeInterface` или еще и в `LoanClientInterface`?
```kotlin
fun getPayments(type: Type?): List<ResponsePaymentInterface>
fun writeOf(paymentRequest: RequestPaymentInterface)
```

2019-04-03 17:59 UTC, malinink commented on src/domain/models/LoanEmployee.kt
> +package domain.models
не уверен что с точки зрения домена - займы должны быть разными моделями

2019-04-03 18:12 UTC, malinink requested changes

2019-04-03 18:12 UTC, malinink commented on src/domain/models/LoanClient.kt
> +) : LoanClientInterface
почему у `LoanEmployee` есть реализация а у `LoanClient` нет?

2019-04-03 18:16 UTC, malinink commented
@Meleorina 
> Где должны лежать функции, только в `LoanEmployeeInterface` или еще и в `LoanClientInterface`?

Честно говоря вообще пока не понимаю зачем два класса, давайте вначале с ними определимся а потом реши где что должно быть?

2019-04-05 19:03 UTC, Meleorina commented on src/domain/models/LoanClient.kt
> +) : LoanClientInterface
`src/domain/models/LoanClient.kt`
Есть, в последнем коммите добавила

2019-04-05 19:34 UTC, Meleorina commented on src/domain/models/LoanEmployee.kt
> +package domain.models
Просто в методе [Получить список займов](https://docs.google.com/document/d/1RiURQhXa6QD7rrq4720uTNWcksZWoBAFmj54RSLcgUg/edit#bookmark=id.cpdcdy6gb1mp) если запрашивает клиент, то приходят урезанные данные `Loan`, соответственно нужно выделить под это отдельную модель, разве не так? 
Ситуация как с платежами в [kotlin-credit](https://github.com/apmath-web/credit-kotlin)

2019-04-11 08:21 UTC, BarracudaPff commented
Про `LoanEmployeeInterface` и `LoanClientInterface`:
В методе `Create` *(создание нового Loan)* приходит урезанный займ, его нужно замаппить в `LoanEmployee` domain'a, но полей не хватает, т.к. их нужно брать из других сервисов, fetcher'ов и тд. поэтому нужен `LoanClient` (имя можно поменять, цель класса немного поменялась)

2019-04-16 18:23 UTC, malinink requested changes

2019-04-16 18:23 UTC, malinink commented on src/com/apmath/loans/domain/models/loans/Loan.kt
> +data class Loan(
Нельзя использовать data class если есть переменные вне конструктора, т.к. по попределению equals будет считаться только по тем параметрам, которые есть в конструкторе.

2019-04-16 18:23 UTC, malinink commented on src/com/apmath/loans/domain/models/loans/LoanCreationData.kt
> +data class LoanCreationData(
предложил бы пока отказаться от использования data, нам он явно нигде всё равно не нужен

2019-04-16 18:23 UTC, malinink commented on src/com/apmath/loans/domain/models/loans/LoanDetailsInterface.kt
> +}
EOF

2019-04-16 18:23 UTC, malinink commented on src/com/apmath/loans/domain/models/loans/LoanInitializationInterface.kt
> +}
EOF

2019-04-16 18:23 UTC, malinink commented on src/com/apmath/loans/domain/models/loans/LoanInterface.kt
> +    val remainBody: Money
вроде бы не надо remainBody? что за кейс?

2019-04-16 18:23 UTC, malinink commented on src/com/apmath/loans/domain/models/loans/LoanInterface.kt
> +    //fun getPayments(type: Type?): List<ResponsePaymentInterface>
договаривались что будут payments и метод, тупо добавляющий платеж в список.

2019-04-16 19:27 UTC, BarracudaPff commented on src/com/apmath/loans/domain/models/loans/LoanCreationData.kt
> +data class LoanCreationData(
Я хотел пометить все классы как `data`, если это модель, и она содержит только данные. На производительность это никак не повлияет (только добавляются методы на этапе компиляции). 
С этим словом должно появиться понимание, что класс - модель, в которой просто хранятся данные

2019-04-17 18:25 UTC, malinink commented on src/com/apmath/loans/domain/models/loans/LoanCreationData.kt
> +data class LoanCreationData(
согласен с тем, что этот префикс должен быть у DTO классов, но не более.

2019-04-17 18:27 UTC, malinink approved these changes

2019-04-17 18:27 UTC, merged