Implement Repository
apmath-web/loans pull request #20
Opened 2019-03-29 12:00 UTC by rgimranova

closes #8

2019-03-29 20:03 UTC, BarracudaPff commented
@rgimranova 
Merge with [dev](https://github.com/apmath-web/loans/tree/dev)

2019-03-29 21:35 UTC, BarracudaPff requested changes
Move classes from `com.apmath.loans.domain` to `domain` and remove `.gitkeep` from `domain`

2019-03-29 22:23 UTC, BarracudaPff approved these changes

2019-04-01 18:31 UTC, malinink approved these changes

2019-04-01 18:32 UTC, merged