Action API: Create new loan
apmath-web/loans pull request #21
Opened 2019-04-11 08:25 UTC by BarracudaPff

- [x] Implement action `Loan.kt`
### Create services and fetchers for tasks:
- [x] Check user id
- [x] Check application id
- [x] Get interest
- [x] Get loan's details
- [x] Response
---
- [ ] Create Exceptions if need

2019-04-23 12:16 UTC, BarracudaPff commented
Запросы из [Mockable](mocable.io)

* [Application get info](http://demo5033957.mockable.io/v1/2001)

* [Calculations init](http://demo5033957.mockable.io/v1/2001)

* [Client get info](http://demo5033957.mockable.io/v1/2001)

2019-04-26 12:55 UTC, malinink requested changes

2019-04-26 12:55 UTC, malinink commented on src/com/apmath/loans/application/v1/actions/Create.kt
> +data class Response(val loanId: Int)
Предлагаю создавать всёже отдельные файлы для классов

2019-04-26 12:55 UTC, malinink commented on src/com/apmath/loans/application/v1/actions/Create.kt
> +suspend fun ApplicationCall.respondError(e: Exception) {
очень похоже на общий метод, который будет много где использоваться, предлагаю его вынести из конкреного экшена

2019-04-26 12:55 UTC, malinink commented on src/com/apmath/loans/application/v1/validators/LoanBuilder.kt
> +}
EOF

2019-04-26 12:55 UTC, malinink commented on src/com/apmath/loans/domain/services/LoanService.kt
> +        return runBlocking {
Зачем?

2019-04-26 12:55 UTC, malinink commented on src/com/apmath/loans/domain/services/LoanService.kt
> +        return runBlocking {
сделейте метод `suspend` и всё будет хорошо

2019-04-26 12:55 UTC, malinink commented on src/com/apmath/loans/infrastructure/fetchers/AbstractFetcher.kt
> +        if (testing)
зачем?

2019-04-26 12:55 UTC, malinink commented on src/com/apmath/loans/infrastructure/fetchers/AbstractFetcher.kt
> +    suspend inline fun <reified T> get(path: String): T {
почему inline ?

2019-04-26 12:55 UTC, malinink commented on src/com/apmath/loans/infrastructure/fetchers/Host.kt
> +    CLIENTS("localhost:8080"),
не уверен что так хранить хорошо, я бы всёже вынес в конфиг, или вы мой ресерч ждете?

2019-04-26 12:55 UTC, malinink commented on test/com/apmath/loans/application/v1/actions/InfoTest.kt
> +    @KtorExperimentalLocationsAPI
а это что? )

2019-04-26 18:50 UTC, BarracudaPff commented on src/com/apmath/loans/domain/services/LoanService.kt
> +        return runBlocking {
Если сделать suspend, то нельзя будет использовать фишки с async.

2019-04-26 18:54 UTC, BarracudaPff commented on src/com/apmath/loans/infrastructure/fetchers/AbstractFetcher.kt
> +    suspend inline fun <reified T> get(path: String): T {
`inline` нужен чтобы использовать `<reified T>`, а он, чтобы использовать использовать T как обычный класс. Иначе будет проблема как в [Validation](https://github.com/apmath-web/validation/blob/e637268119db8774f2aa6aa5811abe67e01dafd7/src/com/apmath/validation/simple/RangeValidator.kt#L10)

2019-04-26 18:56 UTC, BarracudaPff commented on src/com/apmath/loans/infrastructure/fetchers/AbstractFetcher.kt
> +    suspend inline fun <reified T> get(path: String): T {
Правда из-за этого приходится делать `client` public'ом (т.к. public inline не может брать private val)

2019-04-26 18:58 UTC, BarracudaPff commented on test/com/apmath/loans/application/v1/actions/InfoTest.kt
> +    @KtorExperimentalLocationsAPI
из-за того что module - experemental, висел надоедливый warning

2019-04-26 19:09 UTC, malinink commented on src/com/apmath/loans/domain/services/LoanService.kt
> +        return runBlocking {
наоборот, можно будет, а так вы весь сервер заблокируете на момент выполнения блокирующего блока операций.

2019-04-26 19:11 UTC, malinink commented on src/com/apmath/loans/infrastructure/fetchers/AbstractFetcher.kt
> +    suspend inline fun <reified T> get(path: String): T {
in out не помогут? может быть явно без шаблонов реализовать в каждом конкретном классе?

2019-04-27 13:07 UTC, BarracudaPff commented on src/com/apmath/loans/infrastructure/fetchers/AbstractFetcher.kt
> +    suspend inline fun <reified T> get(path: String): T {
Без шаблона придется каждый раз прописывать url, использовать client (а его нельзя в companion object сделать protected)
А так в fetcher'e по суть нужно только прописывать путь и метод
Ну и универсальный же метод, одинаково кода должно быть меньше

2019-04-27 18:54 UTC, malinink requested changes

2019-04-27 18:54 UTC, malinink commented on src/com/apmath/loans/domain/exceptions/ApiException.kt
> +    override val message: String,
точно нужен `overrive val`? если я верно понимаю, можно убрать

2019-04-27 18:54 UTC, malinink commented on src/com/apmath/loans/domain/exceptions/WrongAmountException.kt
> +    ApiException("Loan's amount must be bigger than $max and less than $min", HttpStatusCode.BadRequest)
если я верно понимаю суть формулировки то вы перепутали min с max местами

2019-04-27 18:54 UTC, malinink commented on src/com/apmath/loans/domain/services/LoanService.kt
> +        val applicationResult = GlobalScope.async {
всё ещё не уверен, оставьте  todo чтобы поглядеть как сделать номрально асинхронные запросы с await без глобального скоупа, мне кажется точ это возможною

2019-04-27 18:54 UTC, malinink commented on src/com/apmath/loans/infrastructure/fetchers/AbstractFetcher.kt
> +    suspend inline fun <reified T> get(path: String): T {
todo запилите, если бдет время я постараюсь разобраться, мне не нравится текущее решение

2019-04-27 18:54 UTC, malinink commented on src/com/apmath/loans/infrastructure/fetchers/Host.kt
> +@Suppress("EXPERIMENTAL_API_USAGE")
постараюсь поглядеть, мне кажется что тоже должен быть вариант не руками это делать

2019-04-27 18:54 UTC, malinink commented on src/com/apmath/loans/infrastructure/fetchers/Host.kt
> +@Suppress("EXPERIMENTAL_API_USAGE")
с вас опять же todo

2019-04-27 18:54 UTC, malinink commented on test/com/apmath/loans/application/v1/actions/InfoTest.kt
> +    @KtorExperimentalLocationsAPI
слишком большой PR постарайтесь в следующий раз делать поменьше задачу.
Почти уверен что пропустил очень важные косяки которые "всплывут"

2019-04-28 07:49 UTC, BarracudaPff commented on src/com/apmath/loans/domain/exceptions/ApiException.kt
> +    override val message: String,
без `overrive val` поле будет nullable, а так оно не null 100%

2019-04-28 07:52 UTC, BarracudaPff commented on src/com/apmath/loans/infrastructure/fetchers/Host.kt
> +@Suppress("EXPERIMENTAL_API_USAGE")
Есть еще вариант с [System.getenv()](https://ktor.io/servers/configuration.html) (внизу страницы), но он мне не очень понравился

2019-04-28 07:56 UTC, BarracudaPff commented on test/com/apmath/loans/application/v1/actions/InfoTest.kt
> +    @KtorExperimentalLocationsAPI
С `AbstractFetcher` я и сам не в восторге, но иначе у меня пока не получилось сделать универсальный класс, я тоже еще попробую что-нибудь сделать с ним

2019-04-28 19:18 UTC, malinink approved these changes

2019-04-28 19:18 UTC, merged