Action BL: List of loans
apmath-web/loans pull request #29
Opened 2019-05-08 11:48 UTC by BarracudaPff

- [x] Get data from repository
- [x] Fill response with success data
---
- [x] rewrite domain exceptions
- [x] add api exceptions
- [x] rewrite exception handler
closes #16 
closes #34 

see: apmath-web/calculations#17

2019-05-17 05:44 UTC, malinink requested changes

2019-05-17 05:44 UTC, malinink commented on src/com/apmath/loans/domain/exceptions/BadRequestException.kt
> +class BadRequestException :
Вроде как не должны быть доменными, это App слой

2019-05-17 05:44 UTC, malinink commented on src/com/apmath/loans/domain/services/LoanService.kt
> +        return results.toTypedArray()
Не до конца понял зачем? Почему нельзя возвращать лист?

2019-05-17 05:44 UTC, malinink commented on src/com/apmath/loans/domain/services/LoanService.kt
> +                throw ForbiddenAccessException()
тут да, должны быть доменные ошибки, но как мне кажется они просто должны наследовать либо Exception либо RuntimeException (конечно котлиновские)

А вот в экшене уже они должны перехватываться и заворачиваться в ошибки App слоя, которые нормально отображаются.

2019-05-17 07:56 UTC, BarracudaPff commented on src/com/apmath/loans/domain/services/LoanService.kt
> +                throw ForbiddenAccessException()
Тогда в Action'е будет огромный try-catch на каждую ошибку, плюс можно случайно пропустить какой-то эксепшн. Сейчас же это все в небольшом try-catch блоке, и нужно просто унаследоваться от ApiException, в котором только добавляется код статуса ответа

2019-05-17 07:58 UTC, BarracudaPff commented on src/com/apmath/loans/domain/services/LoanService.kt
> +        return results.toTypedArray()
Вы же говорили что нужно минимизировать возможные ошибки, чтобы в список случайно не добавили лишний платеж. Метод вроде бы не из дорогих

2019-05-17 08:36 UTC, malinink commented on src/com/apmath/loans/domain/services/LoanService.kt
> +                throw ForbiddenAccessException()
но, таков смысл доменной модели, в идеале

2019-05-17 10:23 UTC, BarracudaPff commented on src/com/apmath/loans/domain/services/LoanService.kt
> +                throw ForbiddenAccessException()
Я заодно переписал обработку исключений #34

2019-05-17 18:45 UTC, malinink commented on src/com/apmath/loans/domain/services/LoanService.kt
> +        return results.toTypedArray()
ImmutableList ?

2019-05-17 18:53 UTC, malinink submitted a review, later dismissed

2019-05-17 18:53 UTC, malinink commented on src/com/apmath/loans/domain/services/LoanService.kt
> +        val loans: List<LoanInterface> = repository.getAll()
оставьте TODO чтобы не получать целиком список а потом фильтровать, очевидно должно быть 2 метода а не один в репозитории

2019-05-21 06:06 UTC, malinink approved these changes

2019-05-21 06:06 UTC, merged