Action API: Loan's payments
apmath-web/loans pull request #30
Opened 2019-05-10 22:46 UTC by rgimranova

- [ ] Implement action PaymentList.kt
- [ ] Check loan id
- [ ] Check permissions for loan's info request
- [ ] Validation
- [ ] Response

Closes #11

2019-05-15 08:22 UTC, BarracudaPff requested changes

2019-05-15 08:22 UTC, BarracudaPff commented on src/com/apmath/loans/domain/services/PaymentServiceInterface.kt
> +}
eof

2019-05-15 08:22 UTC, BarracudaPff commented on src/com/apmath/loans/domain/models/MixedLoanIdInterface.kt
> +}
eof

2019-05-15 08:22 UTC, BarracudaPff commented on src/com/apmath/loans/application/v1/actions/ListLoans.kt
> +    val mixed = Mixed(
@malinink suggested moving from model to vars
like [here?](https://github.com/apmath-web/loans/pull/28/commits/0eb8b1bebe77931c75d2151530da926009581289)

2019-05-17 06:10 UTC, malinink requested changes

2019-05-17 06:10 UTC, malinink commented on src/com/apmath/loans/application/v1/actions/ListLoans.kt
> +        respond(validator.messages)
not by specification

2019-05-17 06:10 UTC, malinink commented on src/com/apmath/loans/application/v1/actions/ListLoans.kt
> +            respondError(e)
if there are concrete domain exception you should catch them. Otherwise there is no need of try/catch block here

2019-05-17 06:10 UTC, malinink commented on src/com/apmath/loans/application/v1/actions/PaymentList.kt
> +        request.headers["service"],
I suggest to validate parameters separately

2019-05-17 06:10 UTC, malinink commented on src/com/apmath/loans/application/v1/actions/PaymentList.kt
> +                respondError(e)
also try/catch necessity

2019-05-21 06:07 UTC, malinink commented
@rgimranova merge dev, resolve conflicts

2019-05-21 18:53 UTC, malinink requested changes

2019-05-21 18:53 UTC, malinink commented on src/com/apmath/loans/application/v1/Api.kt
> +            call.v1ListPayments(paymentService)
Предложил бы в метод передавать уже параметр из роута(строковой), чтобы не хардкодить 
как тут https://github.com/apmath-web/applications/blob/056f917839463dff06e465af999f389ef66855cf/src/com/apmath/applications/application/v1/Api.kt#L32

2019-05-21 18:53 UTC, malinink commented on src/com/apmath/loans/application/v1/actions/PaymentList.kt
> +private fun getLoanAttributeId(call: ApplicationCall): Int? {
хедер тоже вынести, в опциональный параметр экшена

2019-05-21 18:53 UTC, malinink commented on src/com/apmath/loans/application/v1/actions/Abstract.kt
> +fun getLoanId(request: ApplicationRequest): Int? {
метод останется, но параметром будет строковое значение `loan`

2019-05-21 18:53 UTC, malinink commented on src/com/apmath/loans/application/v1/models/MixedLoan.kt
> +data class MixedLoan(
мы вроде как обсуждали и пришли к мнению что data классы нам пока не нужны

2019-05-21 18:53 UTC, malinink commented on src/com/apmath/loans/application/v1/models/MixedLoan.kt
> +fun MixedLoan.toMixedLoanId() = MixedLoanId(
предложил бы декларировать метод внутри класса

2019-05-21 18:53 UTC, malinink commented on src/com/apmath/loans/application/v1/models/MixedLoan.kt
> +        Host.APPLICATIONS.value, Host.CALCULATIONS.value, Host.CLIENTS.value -> false
в чем смысл этого условия, я не до конца понимаю?

2019-05-21 18:53 UTC, malinink commented on src/com/apmath/loans/application/v1/validators/MixedLoanBuilder.kt
> +        append("loanIdHeader", ComparableValidator(min = 1))
я бы валидировал поотдельности, и не создавал спевдо сущностей, т.е. тело - да отдельно бы ваидировал. Но каждый параметр - по отдельности, поглядите как мы это делали в `credit-kotlin`

2019-05-21 18:53 UTC, malinink commented on src/com/apmath/loans/infrastructure/Module.kt
> +    singleBy<PaymentServiceInterface, PaymentService>()
Добавьте задачу на использование ENV переменных корректно, как тут https://github.com/apmath-web/applications/pull/10

2019-05-21 19:09 UTC, rgimranova commented on src/com/apmath/loans/application/v1/models/MixedLoan.kt
> +data class MixedLoan(
Да, верно, это нигде не используется сейчас, забыла удалить

2019-05-25 10:07 UTC, malinink requested changes

2019-05-25 10:07 UTC, malinink commented on src/com/apmath/loans/application/v1/Api.kt
> +            call.v1ListPayments(paymentService, parameters["id"]!!)
add clientId here

2019-05-25 10:07 UTC, malinink commented on src/com/apmath/loans/application/v1/actions/Abstract.kt
> +fun getLoanId(request: ApplicationRequest): Int? {
getAndValidate...

2019-05-25 10:07 UTC, malinink commented on src/com/apmath/loans/application/v1/actions/PaymentList.kt
> +    val isService = isService(request)
вроде не нужен

2019-05-26 19:18 UTC, malinink requested changes

2019-05-26 19:18 UTC, malinink commented on src/com/apmath/loans/application/v1/actions/Abstract.kt
> +fun getAndValidateId(parameterId: String): Int? {
возвращаемое значение можно же сделать просто int, тогда можно будет убрать лишний !! в `call.v1ListPayments(paymentService, getAndValidateId(parameters["id"]!!)!!)`
ещё я бы посоветовал этот метод всёже вызывать в экшене, так логичнее получается, проверка прямо в нем, сейчас она неявно вынесена и не очень понятно что валидация есть и она работает

2019-05-26 19:18 UTC, malinink commented on src/com/apmath/loans/application/v1/actions/PaymentList.kt
> +    val loanIdHeader = getLoanId(request)
а чего этот не вынесли?

2019-05-26 19:54 UTC, rgimranova commented on src/com/apmath/loans/application/v1/Api.kt
> +            call.v1ListPayments(paymentService, parameters["id"]!!)
Понимаю, что он может понадобиться для проверки прав доступа, но в спецификации к методу ни clientId не нужен, ни выводить ошибку доступа. Все равно добавлять?

2019-05-26 20:10 UTC, malinink requested changes

2019-05-26 20:10 UTC, malinink commented on src/com/apmath/loans/application/v1/actions/Abstract.kt
> +
если он обязательный то тут API EXception ожидается

2019-05-27 17:37 UTC, malinink approved these changes

2019-05-27 17:37 UTC, merged