Action API: Payment
apmath-web/loans pull request #33
Opened 2019-05-15 08:09 UTC by Meleorina

- [ ] Implement action `Payment.kt`
- [ ] Check loan id
- [ ] Validation
- [ ] Get payment from `calculations`
- [ ] Response
closes: #10

2019-05-15 08:30 UTC, BarracudaPff requested changes

2019-05-15 08:30 UTC, BarracudaPff commented on src/com/apmath/loans/application/v1/actions/Payment.kt
> +    val post = receive<Payment>()
change from `post` to `payment`

2019-05-15 08:30 UTC, BarracudaPff commented on src/com/apmath/loans/application/v1/models/Payment.kt
> +fun Payment.toPayment() = PaymentDomain (
Mayby change from `toPayment()` to `toPaymentDomain()`?

2019-05-15 08:30 UTC, BarracudaPff commented on src/com/apmath/loans/domain/services/PaymentServiceInterface.kt
> +    suspend fun add(payment: Payment) : String
Pass `PaymentInterface`, not `Payment`

2019-05-15 08:30 UTC, BarracudaPff commented on src/com/apmath/loans/domain/services/PaymentService.kt
> +    override suspend fun add(payment: Payment): String {
Same here, use interface

2019-05-15 08:30 UTC, BarracudaPff commented on src/com/apmath/loans/application/v1/models/Payment.kt
> +    date!!,
Set default  date - default current pay date if null

2019-05-21 06:07 UTC, malinink commented
@Meleorina  merge dev, resolve conflicts

2019-05-21 15:37 UTC, BarracudaPff submitted a review, later dismissed

2019-05-21 18:15 UTC, malinink requested changes
@Meleorina merge dev, resolve conflicts

2019-05-21 20:09 UTC, Meleorina commented
@malinink 
@BarracudaPff 
Check merge please

2019-05-21 20:25 UTC, BarracudaPff submitted a review, later dismissed

2019-05-21 20:26 UTC, BarracudaPff commented
Интересно работает гитхаб

![image](https://user-images.githubusercontent.com/18344254/58128207-bd1aee80-7c1f-11e9-8866-30d44330ae32.png)

2019-05-22 06:36 UTC, malinink requested changes

2019-05-22 06:36 UTC, malinink commented on src/com/apmath/loans/application/v1/actions/Payment.kt
> +suspend fun ApplicationCall.v1Payment (paymentService: PaymentServiceInterface){
используйте автоформатирование, где-то ишние пробелы, где-то их нет

2019-05-22 06:36 UTC, malinink commented on src/com/apmath/loans/application/v1/Api.kt
> +        post("{id}/payment"){
Аналогично второму экшену - предлагаю роут параметр передавать отсюда, т.к. он обязательный.
Строкой.

2019-05-22 06:36 UTC, malinink commented on src/com/apmath/loans/application/v1/actions/Payment.kt
> +suspend fun ApplicationCall.v1Payment (paymentService: PaymentServiceInterface){
Тут параметр забирать валидировать и превращать в инт, отдавать корректную ошибку, в случае если не число

2019-05-22 06:36 UTC, malinink commented on src/com/apmath/loans/application/v1/actions/PaymentList.kt
> +suspend fun ApplicationCall.v1ListPayments(paymentService: PaymentServiceInterface){
не до конца понял, это вы смерджили чужую ветку?

2019-05-22 06:36 UTC, malinink commented on src/com/apmath/loans/application/v1/models/MixedLoan.kt
> +data class MixedLoan(
зараза распространяется быстрее раковой опухоли, может быть сделаем разные параметры, ну пожалуйста!

2019-05-22 06:36 UTC, malinink commented on src/com/apmath/loans/application/v1/models/incoming/Payment.kt
> +fun Payment.toPaymentDomain() = PaymentDomain(
сделйте декларацию в самом классе

2019-05-22 06:36 UTC, malinink commented on src/com/apmath/loans/domain/models/MixedLoanIdInterface.kt
> +}
EOF

2019-05-23 21:50 UTC, Meleorina commented on src/com/apmath/loans/application/v1/actions/PaymentList.kt
> +suspend fun ApplicationCall.v1ListPayments(paymentService: PaymentServiceInterface){
Да, случало получилось) Когда заметила - было поздно

2019-05-23 22:00 UTC, Meleorina commented on src/com/apmath/loans/application/v1/models/incoming/Payment.kt
> +fun Payment.toPaymentDomain() = PaymentDomain(
В Котлине для маппинга лучше же использовать Extention Function, доступ к ф-ии будет только у package-scope. И вообще это static функция из Java, а в Котлине по правилам ооп нужно выносить за класс

2019-05-25 10:00 UTC, malinink requested changes

2019-05-25 10:00 UTC, malinink commented on src/com/apmath/loans/application/v1/models/incoming/Payment.kt
> +fun Payment.toPaymentDomain() = PaymentDomain(
url ?

2019-05-25 10:00 UTC, malinink commented on src/com/apmath/loans/application/v1/actions/Payment.kt
> +    payment.clientId = getUserId(request)
getAndValidateClientId

2019-05-25 10:00 UTC, malinink commented on src/com/apmath/loans/application/v1/actions/Payment.kt
> +    payment.loanId = loanId
also

2019-05-25 10:00 UTC, malinink commented on src/com/apmath/loans/application/v1/Api.kt
> +            call.v1Payment(paymentService, parameters["id"]!!)
`clientId`

2019-05-25 19:28 UTC, Meleorina commented on src/com/apmath/loans/application/v1/models/incoming/Payment.kt
> +fun Payment.toPaymentDomain() = PaymentDomain(
https://www.baeldung.com/kotlin-data-objects

2019-05-25 20:35 UTC, BarracudaPff requested changes

2019-05-25 20:35 UTC, BarracudaPff commented on src/com/apmath/loans/domain/services/PaymentServiceInterface.kt
> +    suspend fun add(payment: PaymentInterface) : String
change String to LocalDate

2019-05-26 16:12 UTC, malinink commented
@Meleorina вы править то будете? )

2019-05-28 19:16 UTC, malinink approved these changes

2019-05-28 19:16 UTC, merged