Provide ENV variables support
apmath-web/loans pull request #37
Opened 2019-05-23 19:13 UTC by rgimranova

- [ ] pass some vars into project
- [ ] use new approach to retrieve and pass vars into services

Closes #35

2019-05-23 19:32 UTC, BarracudaPff requested changes

2019-05-23 19:32 UTC, BarracudaPff commented on src/com/apmath/loans/infrastructure/Module.kt
>      //services
add @KtorExperimentalAPI

2019-05-23 19:32 UTC, BarracudaPff commented on src/com/apmath/loans/infrastructure/Module.kt
>      //services
over module

2019-05-23 19:32 UTC, BarracudaPff commented on src/com/apmath/loans/infrastructure/fetchers/AbstractFetcher.kt
>                  path = path
also, add port in all methods

2019-05-23 20:10 UTC, BarracudaPff requested changes

2019-05-23 20:10 UTC, BarracudaPff commented on src/com/apmath/loans/infrastructure/fetchers/AbstractFetcher.kt
> +    val host: String = host
Перенеси val прямо в конструктор для `host` и `port`

2019-05-23 20:28 UTC, BarracudaPff approved these changes

2019-05-25 10:08 UTC, malinink approved these changes

2019-05-25 10:09 UTC, merged