Fix ApplicationFetcher with new specification
apmath-web/loans pull request #44
Opened 2019-05-25 23:00 UTC by rgimranova

- fix method
- rewrite models

Closes #40

2019-05-25 23:12 UTC, BarracudaPff requested changes

2019-05-25 23:12 UTC, BarracudaPff commented on src/com/apmath/loans/infrastructure/fetchers/ApplicationsFetcher.kt
> +        return get("/v1/$clientId/$applicationId")
в спецификации метод  POST, нужно еще модель передать

2019-05-28 10:49 UTC, BarracudaPff commented
@malinink 
check pls

2019-05-28 10:49 UTC, BarracudaPff submitted a review, later dismissed

2019-05-28 19:24 UTC, malinink approved these changes

2019-05-28 19:24 UTC, malinink commented on src/com/apmath/loans/application/v1/actions/Create.kt
> +            when(e.statusCode) {
в идеале ошибки соединения должны отлавливаться в сервисе, и оттуда выбрасываться свои ошибки, которые в свою очередб уже ловятся тут и каким-то образом интерпритируются.

2019-05-28 20:05 UTC, merged